name: Matt Green, That Nigga
markdown: kramdown
permalink: /:year/:month/:day/:title
exclude:
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "Rakefile"
